### ISSUE TITLE
weirdness in OTP generation

### ISSUE THREAD

**Issue by martirsadota** [yourwaifu/yourwaifu#27]
I do *not* know why it happened, but:
![ss 2015-03-21 at 04 50 36](https://cloud.githubusercontent.com/assets/8792260/6764435/9695fb00-cfea-11e4-9e4f-ba605c2c4fac.jpg)

**Comment by TheHowl** [comment]
and what exactly is your problem...?

**Comment by martirsadota** [comment]
note that the series names are listed incorrectly; for instance, Hanako is from Katawa Shoujo but the output says `Kantai Collection`.

**Comment by pixeldesu** [comment]
Ah, I know what the issue is here, I'll fix it asap.

I'm setting an otp['type'] but the default OTP never sets one, so it will always keep the last one set, but with the right OTP characters.
