### ISSUE TITLE
New girl request.

### ISSUE THREAD

**Issue by vipirius** [yourwaifu/yourwaifu#5]
Series: Nisekoi

Kirisaki Chitoge
Onodera Kosaki
Miyamoto Ruri
Tsugumi Seishirou
Tachibana Marika
Paula McCoy
Onodera Haru

Series: K-ON!

Akiyama Mio
Kotobuki Tsumugi
Nakano Azusa
Hirasawa Ui

**Comment by southrop** [comment]
If I'm not mistaken, this was already addressed in 45bb54b so can be closed.
